default: &default
  adapter: postgresql
  encoding: unicode
  username: reverser
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  database: reverser_development

test:
  <<: *default
  database: reverser_test
