# Provide a overwrite file with REVERSER_CUSTOM_CONFIG_PATH
app_name: "Reverser"
# How large should the generated thumbnails be
# This is a bounding box
thumbnail_size: 300
# The server which handles similar images search
# Must respond like https://github.com/danbooru/iqdb
iqdb_server: "http://iqdb:5588"
selenium_url: "http://selenium:4444"

# Only overwriteable through env
custom_config_path: config/reverser_custom_config.yml

log_scraper_requests?: true
# How quickly requests will be sent in seconds. Accepts floats.
# A rate limt of 0.5 means that the next request will be sent at
# least half a second after the previous request finished.
scraper_request_rate_limit: 0

# https://github.com/rails/rails/blob/2d2fdc941e7497ca77f99ce5ad404b6e58f043ef/activesupport/lib/active_support/values/time_zone.rb#L31-L183
time_zone: Berlin

# Disable individual scrapers
artconomy_disabled?: false
artstation_disabled?: false
deviantart_disabled?: false
furaffinity_disabled?: false
furrynetwork_disabled?: false
inkbunny_disabled?: false
newgrounds_disabled?: false
reddit_disabled?: false
sofurry_disabled?: false
twitter_disabled?: false
weasyl_disabled?: false
pixiv_disabled?: false
piczel_disabled?: false
tumblr_disabled?: false
baraag_disabled?: false
pawoo_disabled?: false
itaku_disabled?: false

# Credentials, overwrite in custom file
inkbunny_user:
inkbunny_pass:
# The applications redirect uri must be `http://localhost`
deviantart_client_id:
deviantart_client_secret:
deviantart_user:
deviantart_pass:
e6_user:
e6_apikey:
# Set timezone to 00:00 without daylight saving correction. Modern Theme required. Full Date Format.
furaffinity_user:
furaffinity_pass:
weasyl_apikey:
furrynetwork_user:
furrynetwork_pass:
sofurry_user:
sofurry_pass:
twitter_user:
twitter_pass:
# Only set if your account requires 2fa
twitter_otp_secret:
reddit_client_id:
reddit_client_secret:
pixiv_user:
pixiv_pass:
newgrounds_user:
newgrounds_pass:
tumblr_consumer_key:
tumblr_consumer_secret:
tumblr_oauth_token:
tumblr_oauth_secret:
tumblr_reblog_blog_uuid:
baraag_access_token:
pawoo_access_token:
artconomy_user:
artconomy_pass:
